# https://www.yelp.com/developers/documentation/v3/all_category_list
ALL = [{'alias': 'afghani',
  'country_blacklist': ['TR', 'MX'],
  'parents': ['restaurants'],
  'title': 'Afghan'},
 {'alias': 'african',
  'country_blacklist': ['TR'],
  'parents': ['restaurants'],
  'title': 'African'},
 {'alias': 'andalusian',
  'country_whitelist': ['IT', 'ES'],
  'parents': ['restaurants'],
  'title': 'Andalusian'},
 {'alias': 'arabian',
  'country_blacklist': ['DK'],
  'parents': ['restaurants'],
  'title': 'Arabian'},
 {'alias': 'argentine',
  'country_blacklist': ['FI'],
  'parents': ['restaurants'],
  'title': 'Argentine'},
 {'alias': 'armenian',
  'country_whitelist': ['BE',
                        'CZ',
                        'FR',
                        'AR',
                        'IT',
                        'GB',
                        'PL',
                        'US',
                        'ES',
                        'TR'],
  'parents': ['restaurants'],
  'title': 'Armenian'},
 {'alias': 'asianfusion', 'parents': ['restaurants'], 'title': 'Asian Fusion'},
 {'alias': 'asturian',
  'country_whitelist': ['ES'],
  'parents': ['restaurants'],
  'title': 'Asturian'},
 {'alias': 'australian', 'parents': ['restaurants'], 'title': 'Australian'},
 {'alias': 'austrian',
  'country_blacklist': ['ES', 'DK'],
  'parents': ['restaurants'],
  'title': 'Austrian'},
 {'alias': 'baguettes',
  'country_whitelist': ['MX', 'CZ', 'PT', 'IT', 'SE', 'NO', 'TR', 'DE'],
  'parents': ['restaurants'],
  'title': 'Baguettes'},
 {'alias': 'bangladeshi',
  'country_blacklist': ['MX', 'ES', 'PT', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Bangladeshi'},
 {'alias': 'basque',
  'country_blacklist': ['DK', 'CZ', 'SG', 'PT', 'TR', 'AU'],
  'parents': ['restaurants'],
  'title': 'Basque'},
 {'alias': 'bavarian',
  'country_whitelist': ['AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Bavarian'},
 {'alias': 'bbq',
  'country_blacklist': ['BR', 'AU'],
  'parents': ['restaurants'],
  'title': 'Barbeque'},
 {'alias': 'beergarden',
  'country_whitelist': ['CZ', 'AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Beer Garden'},
 {'alias': 'beerhall',
  'country_whitelist': ['AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Beer Hall'},
 {'alias': 'beisl',
  'country_whitelist': ['AT'],
  'parents': ['restaurants'],
  'title': 'Beisl'},
 {'alias': 'belgian', 'parents': ['restaurants'], 'title': 'Belgian'},
 {'alias': 'bistros',
  'country_blacklist': ['US'],
  'parents': ['restaurants'],
  'title': 'Bistros'},
 {'alias': 'blacksea',
  'country_whitelist': ['TR'],
  'parents': ['restaurants'],
  'title': 'Black Sea'},
 {'alias': 'brasseries',
  'country_blacklist': ['MX', 'AR'],
  'parents': ['restaurants'],
  'title': 'Brasseries'},
 {'alias': 'brazilian', 'parents': ['restaurants'], 'title': 'Brazilian'},
 {'alias': 'breakfast_brunch',
  'parents': ['restaurants'],
  'title': 'Breakfast & Brunch'},
 {'alias': 'british',
  'country_blacklist': ['FI'],
  'parents': ['restaurants'],
  'title': 'British'},
 {'alias': 'buffets', 'parents': ['restaurants'], 'title': 'Buffets'},
 {'alias': 'bulgarian',
  'country_blacklist': ['CA', 'NL', 'SG', 'BR', 'NZ', 'DK', 'NO', 'TR'],
  'parents': ['restaurants'],
  'title': 'Bulgarian'},
 {'alias': 'burgers', 'parents': ['restaurants'], 'title': 'Burgers'},
 {'alias': 'burmese',
  'country_blacklist': ['ES', 'CZ', 'PT', 'FI', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Burmese'},
 {'alias': 'cafes',
  'country_blacklist': ['FI', 'MX', 'ES', 'AR'],
  'parents': ['restaurants'],
  'title': 'Cafes'},
 {'alias': 'cafeteria',
  'country_blacklist': ['CA', 'SE', 'SG', 'BR', 'NZ', 'FR', 'IE'],
  'parents': ['restaurants'],
  'title': 'Cafeteria'},
 {'alias': 'cajun',
  'country_blacklist': ['ES', 'PT', 'AU', 'SG'],
  'parents': ['restaurants'],
  'title': 'Cajun/Creole'},
 {'alias': 'cambodian',
  'country_blacklist': ['ES', 'CZ', 'PT', 'FI', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Cambodian'},
 {'alias': 'canteen',
  'country_whitelist': ['NL',
                        'BE',
                        'CZ',
                        'FI',
                        'DK',
                        'AT',
                        'IT',
                        'PL',
                        'NO',
                        'CH',
                        'JP',
                        'DE'],
  'parents': ['restaurants'],
  'title': 'Canteen'},
 {'alias': 'caribbean',
  'country_blacklist': ['FI', 'TR', 'PT'],
  'parents': ['restaurants'],
  'title': 'Caribbean'},
 {'alias': 'catalan',
  'country_whitelist': ['MX', 'CL', 'PT', 'FR', 'AR', 'IT', 'US', 'ES', 'TR'],
  'parents': ['restaurants'],
  'title': 'Catalan'},
 {'alias': 'cheesesteaks',
  'country_whitelist': ['CA', 'GB', 'NL', 'PL', 'US', 'IE', 'AU'],
  'parents': ['restaurants'],
  'title': 'Cheesesteaks'},
 {'alias': 'chicken_wings',
  'country_blacklist': ['NL',
                        'BE',
                        'CL',
                        'PT',
                        'FR',
                        'FI',
                        'DK',
                        'IT',
                        'NO',
                        'ES',
                        'CH',
                        'JP'],
  'parents': ['restaurants'],
  'title': 'Chicken Wings'},
 {'alias': 'chickenshop',
  'country_blacklist': ['CZ'],
  'parents': ['restaurants'],
  'title': 'Chicken Shop'},
 {'alias': 'chilean',
  'country_whitelist': ['FI', 'BR', 'FR', 'CL'],
  'parents': ['restaurants'],
  'title': 'Chilean'},
 {'alias': 'chinese', 'parents': ['restaurants'], 'title': 'Chinese'},
 {'alias': 'comfortfood',
  'country_whitelist': ['MX', 'CA', 'US', 'CL', 'AR', 'FI', 'JP'],
  'parents': ['restaurants'],
  'title': 'Comfort Food'},
 {'alias': 'corsican',
  'country_whitelist': ['FR', 'BE'],
  'parents': ['restaurants'],
  'title': 'Corsican'},
 {'alias': 'creperies', 'parents': ['restaurants'], 'title': 'Creperies'},
 {'alias': 'cuban',
  'country_blacklist': ['SG', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Cuban'},
 {'alias': 'currysausage',
  'country_whitelist': ['AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Curry Sausage'},
 {'alias': 'cypriot',
  'country_whitelist': ['AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Cypriot'},
 {'alias': 'czech',
  'country_whitelist': ['CA',
                        'BE',
                        'CZ',
                        'FR',
                        'FI',
                        'IE',
                        'DK',
                        'IT',
                        'SE',
                        'GB',
                        'PL',
                        'US',
                        'NO',
                        'DE',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Czech'},
 {'alias': 'czechslovakian',
  'country_whitelist': ['PT', 'MX', 'AR'],
  'parents': ['restaurants'],
  'title': 'Czech/Slovakian'},
 {'alias': 'danish',
  'country_whitelist': ['SE', 'FR', 'DK', 'NO'],
  'parents': ['restaurants'],
  'title': 'Danish'},
 {'alias': 'delis',
  'country_blacklist': ['IT', 'SE', 'NL', 'BE', 'CL', 'PT', 'FR'],
  'parents': ['restaurants'],
  'title': 'Delis'},
 {'alias': 'diners',
  'country_blacklist': ['CZ', 'FI', 'SE', 'AU'],
  'parents': ['restaurants'],
  'title': 'Diners'},
 {'alias': 'dinnertheater',
  'country_blacklist': ['IT', 'NL', 'BE', 'FR', 'JP'],
  'parents': ['restaurants'],
  'title': 'Dinner Theater'},
 {'alias': 'dumplings',
  'country_whitelist': ['CA',
                        'NL',
                        'BE',
                        'SG',
                        'NZ',
                        'IE',
                        'AT',
                        'GB',
                        'PL',
                        'CH',
                        'JP',
                        'DE',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Dumplings'},
 {'alias': 'eastern_european',
  'country_whitelist': ['NO', 'DK', 'CZ', 'FR', 'AU'],
  'parents': ['restaurants'],
  'title': 'Eastern European'},
 {'alias': 'eltern_cafes',
  'country_whitelist': ['AT', 'DE', 'CH'],
  'parents': ['restaurants', 'food'],
  'title': 'Parent Cafes'},
 {'alias': 'eritrean',
  'country_whitelist': ['AT', 'IT', 'US', 'CH', 'DE'],
  'parents': ['restaurants'],
  'title': 'Eritrean'},
 {'alias': 'ethiopian',
  'country_blacklist': ['CZ', 'MX', 'TR', 'SG'],
  'parents': ['restaurants'],
  'title': 'Ethiopian'},
 {'alias': 'filipino',
  'country_blacklist': ['CZ', 'FI', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Filipino'},
 {'alias': 'fischbroetchen',
  'country_whitelist': ['DE'],
  'parents': ['restaurants'],
  'title': 'Fischbroetchen'},
 {'alias': 'fishnchips',
  'country_blacklist': ['PT', 'BR'],
  'parents': ['restaurants'],
  'title': 'Fish & Chips'},
 {'alias': 'flatbread',
  'country_whitelist': ['AT', 'PL', 'CH', 'DE', 'DK'],
  'parents': ['restaurants'],
  'title': 'Flatbread'},
 {'alias': 'fondue',
  'country_blacklist': ['CZ', 'ES', 'DK'],
  'parents': ['restaurants'],
  'title': 'Fondue'},
 {'alias': 'food_court',
  'country_blacklist': ['FI', 'TR', 'TW', 'FR'],
  'parents': ['restaurants'],
  'title': 'Food Court'},
 {'alias': 'foodstands', 'parents': ['restaurants'], 'title': 'Food Stands'},
 {'alias': 'freiduria',
  'country_whitelist': ['CL', 'MX', 'ES', 'AR'],
  'parents': ['restaurants'],
  'title': 'Freiduria'},
 {'alias': 'french', 'parents': ['restaurants'], 'title': 'French'},
 {'alias': 'galician',
  'country_whitelist': ['PT', 'ES'],
  'parents': ['restaurants'],
  'title': 'Galician'},
 {'alias': 'gamemeat',
  'country_blacklist': ['MX',
                        'CA',
                        'HK',
                        'CL',
                        'PT',
                        'BR',
                        'AR',
                        'FI',
                        'TW',
                        'MY',
                        'TR',
                        'JP',
                        'PH'],
  'parents': ['restaurants'],
  'title': 'Game Meat'},
 {'alias': 'gastropubs', 'parents': ['restaurants'], 'title': 'Gastropubs'},
 {'alias': 'georgian',
  'country_whitelist': ['CZ', 'FI', 'AT', 'GB', 'US', 'PL', 'CH', 'DE'],
  'parents': ['restaurants'],
  'title': 'Georgian'},
 {'alias': 'german', 'parents': ['restaurants'], 'title': 'German'},
 {'alias': 'giblets',
  'country_whitelist': ['TR'],
  'parents': ['restaurants'],
  'title': 'Giblets'},
 {'alias': 'gluten_free', 'parents': ['restaurants'], 'title': 'Gluten-Free'},
 {'alias': 'greek', 'parents': ['restaurants'], 'title': 'Greek'},
 {'alias': 'guamanian',
  'country_blacklist': ['MX', 'PL', 'CL', 'FR', 'AR', 'TR', 'JP'],
  'parents': ['restaurants'],
  'title': 'Guamanian'},
 {'alias': 'halal',
  'country_blacklist': ['PT', 'TR'],
  'parents': ['restaurants'],
  'title': 'Halal'},
 {'alias': 'hawaiian',
  'country_blacklist': ['DK', 'CZ', 'PT', 'TR', 'AU'],
  'parents': ['restaurants'],
  'title': 'Hawaiian'},
 {'alias': 'heuriger',
  'country_whitelist': ['AT'],
  'parents': ['restaurants'],
  'title': 'Heuriger'},
 {'alias': 'himalayan',
  'parents': ['restaurants'],
  'title': 'Himalayan/Nepalese'},
 {'alias': 'hkcafe',
  'country_whitelist': ['TW', 'US', 'CA', 'HK'],
  'parents': ['restaurants'],
  'title': 'Hong Kong Style Cafe'},
 {'alias': 'honduran',
  'country_blacklist': ['TR', 'JP'],
  'parents': ['restaurants'],
  'title': 'Honduran'},
 {'alias': 'hotdog', 'parents': ['restaurants'], 'title': 'Hot Dogs'},
 {'alias': 'hotdogs', 'parents': ['restaurants'], 'title': 'Fast Food'},
 {'alias': 'hotpot',
  'country_whitelist': ['CA',
                        'HK',
                        'SG',
                        'BR',
                        'FR',
                        'SE',
                        'TW',
                        'MY',
                        'US',
                        'JP',
                        'PH'],
  'parents': ['restaurants'],
  'title': 'Hot Pot'},
 {'alias': 'hungarian', 'parents': ['restaurants'], 'title': 'Hungarian'},
 {'alias': 'iberian',
  'country_whitelist': ['PT', 'US', 'CA'],
  'parents': ['restaurants'],
  'title': 'Iberian'},
 {'alias': 'indonesian',
  'country_blacklist': ['MX', 'ES'],
  'parents': ['restaurants'],
  'title': 'Indonesian'},
 {'alias': 'indpak', 'parents': ['restaurants'], 'title': 'Indian'},
 {'alias': 'international',
  'country_blacklist': ['IT', 'MY', 'US', 'PH', 'FI', 'TR'],
  'parents': ['restaurants'],
  'title': 'International'},
 {'alias': 'irish', 'parents': ['restaurants'], 'title': 'Irish'},
 {'alias': 'island_pub',
  'country_whitelist': ['SE'],
  'parents': ['restaurants'],
  'title': 'Island Pub'},
 {'alias': 'israeli',
  'country_whitelist': ['CZ', 'AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Israeli'},
 {'alias': 'italian', 'parents': ['restaurants'], 'title': 'Italian'},
 {'alias': 'japanese', 'parents': ['restaurants'], 'title': 'Japanese'},
 {'alias': 'jewish',
  'country_whitelist': ['PL', 'DE', 'IT'],
  'parents': ['restaurants'],
  'title': 'Jewish'},
 {'alias': 'kebab', 'parents': ['restaurants'], 'title': 'Kebab'},
 {'alias': 'kopitiam',
  'country_whitelist': ['SG', 'MY'],
  'parents': ['restaurants'],
  'title': 'Kopitiam'},
 {'alias': 'korean', 'parents': ['restaurants'], 'title': 'Korean'},
 {'alias': 'kosher',
  'country_blacklist': ['PT', 'TR'],
  'parents': ['restaurants'],
  'title': 'Kosher'},
 {'alias': 'kurdish',
  'country_whitelist': ['SE', 'NO'],
  'parents': ['restaurants'],
  'title': 'Kurdish'},
 {'alias': 'laos',
  'country_whitelist': ['AU'],
  'parents': ['restaurants'],
  'title': 'Laos'},
 {'alias': 'laotian',
  'country_blacklist': ['CZ'],
  'parents': ['restaurants'],
  'title': 'Laotian'},
 {'alias': 'latin', 'parents': ['restaurants'], 'title': 'Latin American'},
 {'alias': 'lyonnais',
  'country_whitelist': ['FR', 'BE'],
  'parents': ['restaurants'],
  'title': 'Lyonnais'},
 {'alias': 'malaysian',
  'country_blacklist': ['CZ', 'TR', 'PT', 'ES'],
  'parents': ['restaurants'],
  'title': 'Malaysian'},
 {'alias': 'meatballs',
  'country_whitelist': ['TR', 'NL', 'FR', 'BE'],
  'parents': ['restaurants'],
  'title': 'Meatballs'},
 {'alias': 'mediterranean',
  'parents': ['restaurants'],
  'title': 'Mediterranean'},
 {'alias': 'mexican', 'parents': ['restaurants'], 'title': 'Mexican'},
 {'alias': 'mideastern',
  'country_blacklist': ['BR'],
  'parents': ['restaurants'],
  'title': 'Middle Eastern'},
 {'alias': 'milkbars',
  'country_whitelist': ['PL', 'AU'],
  'parents': ['restaurants'],
  'title': 'Milk Bars'},
 {'alias': 'modern_australian',
  'country_whitelist': ['AU'],
  'parents': ['restaurants'],
  'title': 'Modern Australian'},
 {'alias': 'modern_european',
  'parents': ['restaurants'],
  'title': 'Modern European'},
 {'alias': 'mongolian',
  'country_blacklist': ['FI', 'TR', 'PT', 'ES'],
  'parents': ['restaurants'],
  'title': 'Mongolian'},
 {'alias': 'moroccan',
  'country_blacklist': ['TR'],
  'parents': ['restaurants'],
  'title': 'Moroccan'},
 {'alias': 'newamerican',
  'country_whitelist': ['SE', 'GB', 'US', 'NO', 'IE', 'DK'],
  'parents': ['restaurants'],
  'title': 'American (New)'},
 {'alias': 'newcanadian',
  'country_whitelist': ['CA'],
  'parents': ['restaurants'],
  'title': 'Canadian (New)'},
 {'alias': 'newmexican',
  'country_whitelist': ['US'],
  'parents': ['restaurants'],
  'title': 'New Mexican Cuisine'},
 {'alias': 'newzealand',
  'country_whitelist': ['NZ'],
  'parents': ['restaurants'],
  'title': 'New Zealand'},
 {'alias': 'nicaraguan',
  'country_blacklist': ['CL', 'AR'],
  'parents': ['restaurants'],
  'title': 'Nicaraguan'},
 {'alias': 'nightfood',
  'country_whitelist': ['SE', 'PL', 'NO', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Night Food'},
 {'alias': 'nikkei',
  'country_whitelist': ['MX', 'ES', 'CL', 'BR', 'AR'],
  'parents': ['restaurants'],
  'title': 'Nikkei'},
 {'alias': 'noodles',
  'country_blacklist': ['AT', 'DE', 'CH', 'FR'],
  'parents': ['restaurants'],
  'title': 'Noodles'},
 {'alias': 'norcinerie',
  'country_whitelist': ['IT'],
  'parents': ['restaurants'],
  'title': 'Norcinerie'},
 {'alias': 'norwegian',
  'country_whitelist': ['NO', 'FR'],
  'parents': ['restaurants'],
  'title': 'Traditional Norwegian'},
 {'alias': 'opensandwiches',
  'country_whitelist': ['TR', 'SE', 'NO', 'DK'],
  'parents': ['restaurants'],
  'title': 'Open Sandwiches'},
 {'alias': 'oriental',
  'country_whitelist': ['AT', 'PL', 'PT', 'CH', 'FR', 'DE'],
  'parents': ['restaurants'],
  'title': 'Oriental'},
 {'alias': 'pakistani', 'parents': ['restaurants'], 'title': 'Pakistani'},
 {'alias': 'panasian',
  'country_blacklist': ['IT'],
  'parents': ['restaurants'],
  'title': 'Pan Asian'},
 {'alias': 'parma',
  'country_whitelist': ['AU'],
  'parents': ['restaurants'],
  'title': 'Parma'},
 {'alias': 'persian', 'parents': ['restaurants'], 'title': 'Persian/Iranian'},
 {'alias': 'peruvian',
  'country_blacklist': ['PT', 'TR', 'SG'],
  'parents': ['restaurants'],
  'title': 'Peruvian'},
 {'alias': 'pfcomercial',
  'country_whitelist': ['BR'],
  'parents': ['restaurants'],
  'title': 'PF/Comercial'},
 {'alias': 'pita',
  'country_whitelist': ['TR'],
  'parents': ['restaurants'],
  'title': 'Pita'},
 {'alias': 'pizza', 'parents': ['restaurants'], 'title': 'Pizza'},
 {'alias': 'polish',
  'country_blacklist': ['FI', 'SG'],
  'parents': ['restaurants'],
  'title': 'Polish'},
 {'alias': 'polynesian',
  'country_whitelist': ['US'],
  'parents': ['restaurants'],
  'title': 'Polynesian'},
 {'alias': 'popuprestaurants',
  'country_whitelist': ['BE',
                        'DK',
                        'SE',
                        'MY',
                        'US',
                        'NO',
                        'DE',
                        'PH',
                        'CA',
                        'NL',
                        'HK',
                        'SG',
                        'NZ',
                        'FR',
                        'IE',
                        'GB',
                        'TW',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Pop-Up Restaurants'},
 {'alias': 'portuguese',
  'country_blacklist': ['FI'],
  'parents': ['restaurants'],
  'title': 'Portuguese'},
 {'alias': 'potatoes',
  'country_whitelist': ['AT', 'DE', 'CH', 'AU'],
  'parents': ['restaurants'],
  'title': 'Potatoes'},
 {'alias': 'poutineries',
  'country_whitelist': ['US', 'CA'],
  'parents': ['restaurants'],
  'title': 'Poutineries'},
 {'alias': 'pubfood',
  'country_whitelist': ['AU'],
  'parents': ['restaurants'],
  'title': 'Pub Food'},
 {'alias': 'raw_food', 'parents': ['restaurants'], 'title': 'Live/Raw Food'},
 {'alias': 'riceshop',
  'country_whitelist': ['TR', 'JP'],
  'parents': ['restaurants'],
  'title': 'Rice'},
 {'alias': 'romanian',
  'country_whitelist': ['BE', 'CZ', 'FR', 'AT', 'PL', 'ES', 'CH', 'DE'],
  'parents': ['restaurants'],
  'title': 'Romanian'},
 {'alias': 'rotisserie_chicken',
  'country_whitelist': ['MX',
                        'NL',
                        'BE',
                        'CL',
                        'PT',
                        'BR',
                        'NZ',
                        'FR',
                        'AR',
                        'IT',
                        'PL',
                        'ES',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Rotisserie Chicken'},
 {'alias': 'russian', 'parents': ['restaurants'], 'title': 'Russian'},
 {'alias': 'salad', 'parents': ['restaurants'], 'title': 'Salad'},
 {'alias': 'sandwiches', 'parents': ['restaurants'], 'title': 'Sandwiches'},
 {'alias': 'scandinavian',
  'country_blacklist': ['PT'],
  'parents': ['restaurants'],
  'title': 'Scandinavian'},
 {'alias': 'schnitzel',
  'country_whitelist': ['AT', 'PL', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Schnitzel'},
 {'alias': 'scottish',
  'country_whitelist': ['AT', 'CA', 'GB', 'US', 'CH', 'DE', 'IE'],
  'parents': ['restaurants'],
  'title': 'Scottish'},
 {'alias': 'seafood', 'parents': ['restaurants'], 'title': 'Seafood'},
 {'alias': 'serbocroatian',
  'country_whitelist': ['BE',
                        'CL',
                        'CZ',
                        'FR',
                        'AR',
                        'AT',
                        'IT',
                        'SE',
                        'PL',
                        'CH',
                        'DE'],
  'parents': ['restaurants'],
  'title': 'Serbo Croatian'},
 {'alias': 'signature_cuisine',
  'country_whitelist': ['MX', 'CL', 'PT', 'AR', 'DK', 'SE', 'NO', 'ES'],
  'parents': ['restaurants'],
  'title': 'Signature Cuisine'},
 {'alias': 'singaporean',
  'country_blacklist': ['ES', 'CZ', 'PT', 'FI', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Singaporean'},
 {'alias': 'slovakian',
  'country_whitelist': ['CA',
                        'BE',
                        'CZ',
                        'FR',
                        'IE',
                        'IT',
                        'GB',
                        'PL',
                        'US',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Slovakian'},
 {'alias': 'somali',
  'country_whitelist': ['AT', 'IT', 'PL', 'US', 'CH', 'DE'],
  'parents': ['restaurants'],
  'title': 'Somali'},
 {'alias': 'soulfood',
  'country_whitelist': ['CA', 'NL', 'IE', 'SE', 'GB', 'PL', 'US', 'NO', 'ES'],
  'parents': ['restaurants'],
  'title': 'Soul Food'},
 {'alias': 'soup', 'parents': ['restaurants'], 'title': 'Soup'},
 {'alias': 'southern',
  'country_whitelist': ['CA', 'NL', 'NZ', 'IE', 'SE', 'GB', 'PL', 'US', 'TR'],
  'parents': ['restaurants'],
  'title': 'Southern'},
 {'alias': 'spanish', 'parents': ['restaurants'], 'title': 'Spanish'},
 {'alias': 'srilankan',
  'country_blacklist': ['CZ'],
  'parents': ['restaurants'],
  'title': 'Sri Lankan'},
 {'alias': 'steak', 'parents': ['restaurants'], 'title': 'Steakhouses'},
 {'alias': 'sud_ouest',
  'country_whitelist': ['FR', 'BE'],
  'parents': ['restaurants'],
  'title': 'French Southwest'},
 {'alias': 'supperclubs',
  'country_whitelist': ['US', 'CA', 'ES', 'GB'],
  'parents': ['restaurants'],
  'title': 'Supper Clubs'},
 {'alias': 'sushi', 'parents': ['restaurants'], 'title': 'Sushi Bars'},
 {'alias': 'swabian',
  'country_whitelist': ['AT', 'DE', 'CH'],
  'parents': ['restaurants'],
  'title': 'Swabian'},
 {'alias': 'swedish',
  'country_whitelist': ['SE'],
  'parents': ['restaurants'],
  'title': 'Swedish'},
 {'alias': 'swissfood',
  'country_whitelist': ['MX', 'ES', 'CL', 'CZ', 'CH', 'AR', 'DE'],
  'parents': ['restaurants'],
  'title': 'Swiss Food'},
 {'alias': 'syrian', 'parents': ['restaurants'], 'title': 'Syrian'},
 {'alias': 'tabernas',
  'country_whitelist': ['PT', 'TR', 'ES'],
  'parents': ['restaurants'],
  'title': 'Tabernas'},
 {'alias': 'taiwanese',
  'country_blacklist': ['ES', 'CZ', 'PT', 'FI', 'TR'],
  'parents': ['restaurants'],
  'title': 'Taiwanese'},
 {'alias': 'tapas',
  'country_blacklist': ['FI', 'AU', 'SG'],
  'parents': ['restaurants'],
  'title': 'Tapas Bars'},
 {'alias': 'tapasmallplates',
  'parents': ['restaurants'],
  'title': 'Tapas/Small Plates'},
 {'alias': 'tavolacalda',
  'country_whitelist': ['IT'],
  'parents': ['restaurants'],
  'title': 'Tavola Calda'},
 {'alias': 'tex-mex',
  'country_blacklist': ['ES', 'PT', 'AU', 'DK'],
  'parents': ['restaurants'],
  'title': 'Tex-Mex'},
 {'alias': 'thai', 'parents': ['restaurants'], 'title': 'Thai'},
 {'alias': 'tradamerican',
  'parents': ['restaurants'],
  'title': 'American (Traditional)'},
 {'alias': 'traditional_swedish',
  'country_whitelist': ['FI', 'SE'],
  'parents': ['restaurants'],
  'title': 'Traditional Swedish'},
 {'alias': 'trattorie',
  'country_whitelist': ['IT', 'PL', 'CL', 'CH', 'FR', 'AR'],
  'parents': ['restaurants'],
  'title': 'Trattorie'},
 {'alias': 'turkish', 'parents': ['restaurants'], 'title': 'Turkish'},
 {'alias': 'ukrainian',
  'country_blacklist': ['ES', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Ukrainian'},
 {'alias': 'uzbek',
  'country_whitelist': ['CZ', 'US'],
  'parents': ['restaurants'],
  'title': 'Uzbek'},
 {'alias': 'vegan', 'parents': ['restaurants'], 'title': 'Vegan'},
 {'alias': 'vegetarian', 'parents': ['restaurants'], 'title': 'Vegetarian'},
 {'alias': 'venison',
  'country_whitelist': ['CA',
                        'CZ',
                        'SG',
                        'NZ',
                        'IE',
                        'DK',
                        'IT',
                        'GB',
                        'PL',
                        'NO',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Venison'},
 {'alias': 'vietnamese', 'parents': ['restaurants'], 'title': 'Vietnamese'},
 {'alias': 'waffles', 'parents': ['restaurants'], 'title': 'Waffles'},
 {'alias': 'wok',
  'country_blacklist': ['CA',
                        'HK',
                        'SG',
                        'BR',
                        'NZ',
                        'AR',
                        'IE',
                        'IT',
                        'GB',
                        'TW',
                        'PL',
                        'US',
                        'TR',
                        'JP',
                        'AU'],
  'parents': ['restaurants'],
  'title': 'Wok'},
 {'alias': 'wraps',
  'country_whitelist': ['SE', 'US', 'NO', 'CZ', 'PT', 'TR', 'DK'],
  'parents': ['restaurants'],
  'title': 'Wraps'},
 {'alias': 'yugoslav',
  'country_whitelist': ['IT', 'SE', 'BE', 'PT', 'FR', 'AU'],
  'parents': ['restaurants'],
  'title': 'Yugoslav'}]
